/* ─── 简化 emoji 字典（常用表情，名字 -> 字符） ───
 * 输入 :name 触发 Suggestion 时使用。键名为小写英文（含下划线）。
 */

export const emojisToName: { name: string; emoji: string }[] = [
  { name: "smile", emoji: "😄" },
  { name: "smile_eye", emoji: "😃" },
  { name: "joy", emoji: "😂" },
  { name: "rofl", emoji: "🤣" },
  { name: "heart_eyes", emoji: "😍" },
  { name: "kiss", emoji: "😘" },
  { name: "wink", emoji: "😉" },
  { name: "blush", emoji: "😊" },
  { name: "innocent", emoji: "😇" },
  { name: "thinking", emoji: "🤔" },
  { name: "expressionless", emoji: "😑" },
  { name: "neutral", emoji: "😐" },
  { name: "rolling_eyes", emoji: "🙄" },
  { name: "smirk", emoji: "😏" },
  { name: "unamused", emoji: "😒" },
  { name: "sleeping", emoji: "😴" },
  { name: "mask", emoji: "😷" },
  { name: "sweat", emoji: "😓" },
  { name: "cry", emoji: "😢" },
  { name: "sob", emoji: "😭" },
  { name: "scream", emoji: "😱" },
  { name: "angry", emoji: "😠" },
  { name: "rage", emoji: "😡" },
  { name: "persevere", emoji: "😣" },
  { name: "confounded", emoji: "😖" },
  { name: "confused", emoji: "😕" },
  { name: "worried", emoji: "😟" },
  { name: "astonished", emoji: "😲" },
  { name: "flushed", emoji: "😳" },
  { name: "dizzy", emoji: "😵" },
  { name: "star_struck", emoji: "🤩" },
  { name: "zany", emoji: "🤪" },
  { name: "shush", emoji: "🤫" },
  { name: "shrug", emoji: "🤷" },
  { name: "nerd", emoji: "🤓" },
  { name: "cool", emoji: "😎" },
  { name: "party", emoji: "🥳" },
  { name: "thumbsup", emoji: "👍" },
  { name: "thumbsdown", emoji: "👎" },
  { name: "ok_hand", emoji: "👌" },
  { name: "clap", emoji: "👏" },
  { name: "wave", emoji: "👋" },
  { name: "point_up", emoji: "☝️" },
  { name: "point_down", emoji: "👇" },
  { name: "point_left", emoji: "👈" },
  { name: "point_right", emoji: "👉" },
  { name: "raised_hand", emoji: "✋" },
  { name: "vulcan", emoji: "🖖" },
  { name: "muscle", emoji: "💪" },
  { name: "pray", emoji: "🙏" },
  { name: "handshake", emoji: "🤝" },
  { name: "fist", emoji: "✊" },
  { name: "victory", emoji: "✌️" },
  { name: "metal", emoji: "🤘" },
  { name: "writing", emoji: "✍️" },
  { name: "heart", emoji: "❤️" },
  { name: "orange_heart", emoji: "🧡" },
  { name: "yellow_heart", emoji: "💛" },
  { name: "green_heart", emoji: "💚" },
  { name: "blue_heart", emoji: "💙" },
  { name: "purple_heart", emoji: "💜" },
  { name: "black_heart", emoji: "🖤" },
  { name: "white_heart", emoji: "🤍" },
  { name: "broken_heart", emoji: "💔" },
  { name: "two_hearts", emoji: "💕" },
  { name: "sparkling_heart", emoji: "💖" },
  { name: "cupid", emoji: "💘" },
  { name: "gift_heart", emoji: "💝" },
  { name: "revolving_hearts", emoji: "💞" },
  { name: "heartbeat", emoji: "💓" },
  { name: "fire", emoji: "🔥" },
  { name: "sparkles", emoji: "✨" },
  { name: "star", emoji: "⭐" },
  { name: "star2", emoji: "🌟" },
  { name: "dizzy_star", emoji: "💫" },
  { name: "boom", emoji: "💥" },
  { name: "sweat_drops", emoji: "💦" },
  { name: "dash", emoji: "💨" },
  { name: "anger", emoji: "💢" },
  { name: "100", emoji: "💯" },
  { name: "battery", emoji: "🔋" },
  { name: "robot", emoji: "🤖" },
  { name: "ghost", emoji: "👻" },
  { name: "skull", emoji: "💀" },
  { name: "alien", emoji: "👽" },
  { name: "clown", emoji: "🤡" },
  { name: "jack_o", emoji: "🎃" },
  { name: "cat", emoji: "🐱" },
  { name: "dog", emoji: "🐶" },
  { name: "mouse", emoji: "🐭" },
  { name: "hamster", emoji: "🐹" },
  { name: "rabbit", emoji: "🐰" },
  { name: "fox", emoji: "🦊" },
  { name: "bear", emoji: "🐻" },
  { name: "panda", emoji: "🐼" },
  { name: "koala", emoji: "🐨" },
  { name: "tiger", emoji: "🐯" },
  { name: "lion", emoji: "🦁" },
  { name: "cow", emoji: "🐮" },
  { name: "pig", emoji: "🐷" },
  { name: "frog", emoji: "🐸" },
  { name: "monkey", emoji: "🐵" },
  { name: "chicken", emoji: "🐔" },
  { name: "penguin", emoji: "🐧" },
  { name: "bird", emoji: "🐦" },
  { name: "duck", emoji: "🦆" },
  { name: "owl", emoji: "🦉" },
  { name: "butterfly", emoji: "🦋" },
  { name: "bee", emoji: "🐝" },
  { name: "turtle", emoji: "🐢" },
  { name: "snake", emoji: "🐍" },
  { name: "fish", emoji: "🐟" },
  { name: "tropical", emoji: "🐠" },
  { name: "blowfish", emoji: "🐡" },
  { name: "octopus", emoji: "🐙" },
  { name: "dolphin", emoji: "🐬" },
  { name: "whale", emoji: "🐳" },
  { name: "whale2", emoji: "🐋" },
  { name: "crocodile", emoji: "🐊" },
  { name: "leopard", emoji: "🐆" },
  { name: "tiger2", emoji: "🐆" },
  { name: "zebra", emoji: "🦓" },
  { name: "giraffe", emoji: "🦒" },
  { name: "elephant", emoji: "🐘" },
  { name: "rhino", emoji: "🦏" },
  { name: "hippo", emoji: "🦛" },
  { name: "burger", emoji: "🍔" },
  { name: "fries", emoji: "🍟" },
  { name: "pizza", emoji: "🍕" },
  { name: "hotdog", emoji: "🌭" },
  { name: "sandwich", emoji: "🥪" },
  { name: "taco", emoji: "🌮" },
  { name: "burrito", emoji: "🌯" },
  { name: "egg", emoji: "🍳" },
  { name: "soup", emoji: "🍲" },
  { name: "curry", emoji: "🍛" },
  { name: "sushi", emoji: "🍣" },
  { name: "ramen", emoji: "🍜" },
  { name: "doughnut", emoji: "🍩" },
  { name: "cookie", emoji: "🍪" },
  { name: "cake", emoji: "🍰" },
  { name: "chocolate", emoji: "🍫" },
  { name: "candy", emoji: "🍬" },
  { name: "lollipop", emoji: "🍭" },
  { name: "coffee", emoji: "☕" },
  { name: "tea", emoji: "🍵" },
  { name: "beer", emoji: "🍺" },
  { name: "wine", emoji: "🍷" },
  { name: "cocktail", emoji: "🍸" },
  { name: "tropical_drink", emoji: "🍹" },
  { name: "champagne", emoji: "🍾" },
  { name: "milk", emoji: "🥛" },
  { name: "icecream", emoji: "🍦" },
  { name: "apple", emoji: "🍎" },
  { name: "green_apple", emoji: "🍏" },
  { name: "pear", emoji: "🍐" },
  { name: "orange", emoji: "🍊" },
  { name: "lemon", emoji: "🍋" },
  { name: "banana", emoji: "🍌" },
  { name: "watermelon", emoji: "🍉" },
  { name: "grapes", emoji: "🍇" },
  { name: "strawberry", emoji: "🍓" },
  { name: "melon", emoji: "🍈" },
  { name: "cherries", emoji: "🍒" },
  { name: "peach", emoji: "🍑" },
  { name: "pineapple", emoji: "🍍" },
  { name: "tomato", emoji: "🍅" },
  { name: "eggplant", emoji: "🍆" },
  { name: "avocado", emoji: "🥑" },
  { name: "broccoli", emoji: "🥦" },
  { name: "cucumber", emoji: "🥒" },
  { name: "pepper", emoji: "🌶️" },
  { name: "corn", emoji: "🌽" },
  { name: "carrot", emoji: "🥕" },
  { name: "rose", emoji: "🌹" },
  { name: "tulip", emoji: "🌷" },
  { name: "sunflower", emoji: "🌻" },
  { name: "blossom", emoji: "🌼" },
  { name: "cherry_blossom", emoji: "🌸" },
  { name: "white_flower", emoji: "💮" },
  { name: "hibiscus", emoji: "🌺" },
  { name: "palm", emoji: "🌴" },
  { name: "cactus", emoji: "🌵" },
  { name: "tree", emoji: "🌳" },
  { name: "evergreen", emoji: "🌲" },
  { name: "maple_leaf", emoji: "🍁" },
  { name: "leaves", emoji: "🍃" },
  { name: "mushroom", emoji: "🍄" },
  { name: "globe", emoji: "🌍" },
  { name: "moon", emoji: "🌙" },
  { name: "new_moon", emoji: "🌑" },
  { name: "full_moon", emoji: "🌕" },
  { name: "sun", emoji: "☀️" },
  { name: "cloud", emoji: "☁️" },
  { name: "umbrella", emoji: "☂️" },
  { name: "snowflake", emoji: "❄️" },
  { name: "snowman", emoji: "⛄" },
  { name: "zap", emoji: "⚡" },
  { name: "rainbow", emoji: "🌈" },
  { name: "ocean", emoji: "🌊" },
  { name: "volcano", emoji: "🌋" },
  { name: "mountain", emoji: "⛰️" },
  { name: "camping", emoji: "🏕️" },
  { name: "tent", emoji: "⛺" },
  { name: "house", emoji: "🏠" },
  { name: "school", emoji: "🏫" },
  { name: "hospital", emoji: "🏥" },
  { name: "bank", emoji: "🏦" },
  { name: "church", emoji: "⛪" },
  { name: "mosque", emoji: "🕌" },
  { name: "synagogue", emoji: "🕍" },
  { name: "castle", emoji: "🏰" },
  { name: "bridge", emoji: "🌉" },
  { name: "ferris_wheel", emoji: "🎡" },
  { name: "roller_coaster", emoji: "🎢" },
  { name: "carousel", emoji: "🎠" },
  { name: "fountain", emoji: "⛲" },
  { name: "umbrella2", emoji: "⛱️" },
  { name: "beach", emoji: "🏖️" },
  { name: "snow_mountain", emoji: "🏔️" },
  { name: "car", emoji: "🚗" },
  { name: "taxi", emoji: "🚕" },
  { name: "bus", emoji: "🚌" },
  { name: "trolleybus", emoji: "🚎" },
  { name: "ambulance", emoji: "🚑" },
  { name: "fire_engine", emoji: "🚒" },
  { name: "police_car", emoji: "🚓" },
  { name: "truck", emoji: "🚚" },
  { name: "tractor", emoji: "🚜" },
  { name: "bicycle", emoji: "🚲" },
  { name: "scooter", emoji: "🛴" },
  { name: "motorcycle", emoji: "🏍️" },
  { name: "train", emoji: "🚆" },
  { name: "bullet_train", emoji: "🚄" },
  { name: "metro", emoji: "🚇" },
  { name: "light_rail", emoji: "🚈" },
  { name: "tram", emoji: "🚊" },
  { name: "station", emoji: "🚉" },
  { name: "airplane", emoji: "✈️" },
  { name: "rocket", emoji: "🚀" },
  { name: "helicopter", emoji: "🚁" },
  { name: "sailboat", emoji: "⛵" },
  { name: "ship", emoji: "🚢" },
  { name: "anchor", emoji: "⚓" },
  { name: "watch", emoji: "⌚" },
  { name: "phone", emoji: "📱" },
  { name: "computer", emoji: "💻" },
  { name: "keyboard", emoji: "⌨️" },
  { name: "desktop", emoji: "🖥️" },
  { name: "printer", emoji: "🖨️" },
  { name: "mouse", emoji: "🖱️" },
  { name: "camera", emoji: "📷" },
  { name: "video_camera", emoji: "📹" },
  { name: "tv", emoji: "📺" },
  { name: "radio", emoji: "📻" },
  { name: "microphone", emoji: "🎤" },
  { name: "headphone", emoji: "🎧" },
  { name: "alarm", emoji: "⏰" },
  { name: "clock", emoji: "🕰️" },
  { name: "stopwatch", emoji: "⏱️" },
  { name: "hourglass", emoji: "⌛" },
  { name: "book", emoji: "📖" },
  { name: "open_book", emoji: "📚" },
  { name: "notebook", emoji: "📓" },
  { name: "ledger", emoji: "📒" },
  { name: "scroll", emoji: "📜" },
  { name: "memo", emoji: "📝" },
  { name: "date", emoji: "📅" },
  { name: "calendar", emoji: "📆" },
  { name: "card_index", emoji: "📇" },
  { name: "chart_up", emoji: "📈" },
  { name: "chart_down", emoji: "📉" },
  { name: "bar_chart", emoji: "📊" },
  { name: "clipboard", emoji: "📋" },
  { name: "pushpin", emoji: "📌" },
  { name: "paperclip", emoji: "📎" },
  { name: "lock", emoji: "🔒" },
  { name: "unlock", emoji: "🔓" },
  { name: "key", emoji: "🔑" },
  { name: "hammer", emoji: "🔨" },
  { name: "wrench", emoji: "🔧" },
  { name: "screwdriver", emoji: "🛠️" },
  { name: "magnifier", emoji: "🔍" },
  { name: "bulb", emoji: "💡" },
  { name: "flashlight", emoji: "🔦" },
  { name: "bomb", emoji: "💣" },
  { name: "knife", emoji: "🔪" },
  { name: "gun", emoji: "🔫" },
  { name: "money", emoji: "💰" },
  { name: "dollar", emoji: "💵" },
  { name: "yen", emoji: "💴" },
  { name: "pound", emoji: "💷" },
  { name: "euro", emoji: "💶" },
  { name: "credit_card", emoji: "💳" },
  { name: "gem", emoji: "💎" },
  { name: "scales", emoji: "⚖️" },
  { name: "ring", emoji: "💍" },
  { name: "bell", emoji: "🔔" },
  { name: "no_bell", emoji: "🔕" },
  { name: "bookmark", emoji: "🔖" },
  { name: "link", emoji: "🔗" },
  { name: "button", emoji: "🔘" },
  { name: "scroll2", emoji: "📃" },
  { name: "page", emoji: "📄" },
  { name: "flag", emoji: "🚩" },
  { name: "white_flag", emoji: "🏳️" },
  { name: "black_flag", emoji: "🏴" },
  { name: "rainbow_flag", emoji: "🏳️‍🌈" },
  { name: "check_mark", emoji: "✅" },
  { name: "cross_mark", emoji: "❌" },
  { name: "warning", emoji: "⚠️" },
  { name: "no_entry", emoji: "⛔" },
  { name: "recycle", emoji: "♻️" },
  { name: "prohibited", emoji: "🚫" },
  { name: "info", emoji: "ℹ️" },
  { name: "question", emoji: "❓" },
  { name: "exclamation", emoji: "❗" },
  { name: "plus", emoji: "➕" },
  { name: "minus", emoji: "➖" },
  { name: "arrow_right", emoji: "➡️" },
  { name: "arrow_left", emoji: "⬅️" },
  { name: "arrow_up", emoji: "⬆️" },
  { name: "arrow_down", emoji: "⬇️" },
  { name: "end", emoji: "🔚" },
  { name: "back", emoji: "🔙" },
  { name: "on", emoji: "🔛" },
  { name: "soon", emoji: "🔜" },
  { name: "top", emoji: "🔝" },
  { name: "new", emoji: "🆕" },
  { name: "ok", emoji: "🆗" },
  { name: "cool2", emoji: "🆒" },
  { name: "free", emoji: "🆓" },
  { name: "sos", emoji: "🆘" },
  { name: "ball", emoji: "⚽" },
  { name: "basketball", emoji: "🏀" },
  { name: "football", emoji: "🏈" },
  { name: "baseball", emoji: "⚾" },
  { name: "tennis", emoji: "🎾" },
  { name: "volleyball", emoji: "🏐" },
  { name: "billiards", emoji: "🎱" },
  { name: "bowling", emoji: "🎳" },
  { name: "trophy", emoji: "🏆" },
  { name: "medal", emoji: "🏅" },
  { name: "ribbon", emoji: "🎗️" },
  { name: "ticket", emoji: "🎫" },
  { name: "game", emoji: "🎮" },
  { name: "dart", emoji: "🎯" },
  { name: "puzzle", emoji: "🧩" },
  { name: "art", emoji: "🎨" },
  { name: "guitar", emoji: "🎸" },
  { name: "violin", emoji: "🎻" },
  { name: "drum", emoji: "🥁" },
  { name: "sax", emoji: "🎷" },
  { name: "trumpet", emoji: "🎺" },
  { name: "music", emoji: "🎵" },
  { name: "note", emoji: "🎶" },
  { name: "headphone2", emoji: "🎧" },
  { name: "rock", emoji: "🤘" },
  { name: "metal2", emoji: "🤟" },
  { name: "v2", emoji: "✌" },
  { name: "raised_hands", emoji: "🙌" },
  { name: "folded_hands", emoji: "🤲" },
  { name: "call_me", emoji: "🤙" },
  { name: "mechanical_arm", emoji: "🦾" },
  { name: "mechanical_leg", emoji: "🦿" },
  { name: "red_hair", emoji: "🦰" },
  { name: "curly_hair", emoji: "🦱" },
  { name: "white_hair", emoji: "🦳" },
  { name: "bald", emoji: "🦲" },
  { name: "two_women", emoji: "👯" },
  { name: "bath", emoji: "🛀" },
  { name: "sleep", emoji: "🛌" },
  { name: "walking", emoji: "🚶" },
  { name: "running", emoji: "🏃" },
  { name: "dancer", emoji: "💃" },
  { name: "man_dancing", emoji: "🕺" },
  { name: "people_wrestling", emoji: "🤼" },
  { name: "people_holding_hands", emoji: "🧑‍🤝‍🧑" },
  { name: "ear", emoji: "👂" },
  { name: "nose", emoji: "👃" },
  { name: "eyes", emoji: "👀" },
  { name: "eye", emoji: "👁️" },
  { name: "brain", emoji: "🧠" },
  { name: "tooth", emoji: "🦷" },
  { name: "bone", emoji: "🦴" },
  { name: "foot", emoji: "🦶" },
  { name: "leg", emoji: "🦵" },
  { name: "hand", emoji: "✋" },
  { name: "lips", emoji: "👄" },
  { name: "tongue", emoji: "👅" },
  { name: "no_pedestrians", emoji: "🚷" },
  { name: "no_bicycles", emoji: "🚳" },
  { name: "no_phones", emoji: "📵" },
  { name: "wc", emoji: "🚻" },
  { name: "mens", emoji: "🚹" },
  { name: "womens", emoji: "🚺" },
  { name: "baby_symbol", emoji: "🚼" },
  { name: "potable_water", emoji: "🚰" },
  { name: "put_litter", emoji: "🚮" },
  { name: "passport_control", emoji: "🛂" },
  { name: "customs", emoji: "🛃" },
  { name: "baggage_claim", emoji: "🛄" },
  { name: "left_luggage", emoji: "🛅" },
  { name: "accept", emoji: "🉑" },
  { name: "ideograph_advantage", emoji: "🉐" },
  { name: "congratulations", emoji: "㊗️" },
  { name: "secret", emoji: "㊙️" },
  { name: "m", emoji: "Ⓜ️" },
  { name: "u", emoji: "🆄" },
  { name: "vs", emoji: "🆚" },
  { name: "cl", emoji: "🆑" },
  { name: "id", emoji: "🆔" },
  { name: "a", emoji: "🅰️" },
  { name: "b", emoji: "🅱️" },
  { name: "ab", emoji: "🆎" },
  { name: "o2", emoji: "🅾️" },
  { name: "ng", emoji: "🆖" },
  { name: "x", emoji: "❎" },
  { name: "o", emoji: "🅾" },
  { name: "koko", emoji: "🈁" },
  { name: "sa", emoji: "🈂️" },
  { name: "u6708", emoji: "🈷️" },
  { name: "u5272", emoji: "🈹" },
  { name: "u7121", emoji: "🈚" },
  { name: "u6307", emoji: "🈯" },
  { name: "u7533", emoji: "🈸" },
  { name: "u5408", emoji: "🈴" },
  { name: "u7981", emoji: "🈲" },
  { name: "u7a7a", emoji: "🈳" },
  { name: "restroom", emoji: "🚻" },
  { name: "mens2", emoji: "🚹" },
  { name: "womens2", emoji: "🚺" },
  { name: "womens3", emoji: "🚺" },
  { name: "mens3", emoji: "🚹" },
  { name: "man", emoji: "👨" },
  { name: "woman", emoji: "👩" },
  { name: "boy", emoji: "👦" },
  { name: "girl", emoji: "👧" },
  { name: "older_man", emoji: "👴" },
  { name: "older_woman", emoji: "👵" },
  { name: "baby", emoji: "👶" },
  { name: "santa", emoji: "🎅" },
  { name: "angel", emoji: "👼" },
  { name: "construction_worker", emoji: "👷" },
  { name: "princess", emoji: "👸" },
  { name: "guard", emoji: "💂" },
  { name: "detective", emoji: "🕵️" },
  { name: "person_tipping_hand", emoji: "💁" },
  { name: "person_raising_hand", emoji: "🙋" },
  { name: "person_pouting", emoji: "🙎" },
  { name: "person_frowning", emoji: "🙍" },
  { name: "person_gesturing_no", emoji: "🙅" },
  { name: "person_gesturing_ok", emoji: "🙆" },
  { name: "person_bowing", emoji: "🙇" },
  { name: "person_facepalming", emoji: "🤦" },
  { name: "person_shrugging", emoji: "🤷" },
  { name: "family", emoji: "👪" },
  { name: "family_man_woman_boy", emoji: "👨‍👩‍👦" },
  { name: "couple", emoji: "👨‍❤️‍👨" },
  { name: "couple_with_heart", emoji: "💑" },
  { name: "kiss_mm", emoji: "👨‍❤️‍💋‍👨" },
  { name: "kiss_ww", emoji: "👩‍❤️‍💋‍👩" },
  { name: "couples_heart", emoji: "👩‍❤️‍💋‍👨" },
  { name: "two_men_holding_hands", emoji: "👬" },
  { name: "two_women_holding_hands", emoji: "👭" },
  { name: "man_and_woman_holding_hands", emoji: "👫" },
  { name: "people_with_bunny_ears_partying", emoji: "👯" },
  { name: "woman_with_ears", emoji: "👯‍♀️" },
  { name: "man_with_ears", emoji: "👯‍♂️" },
];

/* ─── 全量 emoji 字典（约 1900 个，数据移植自 https://github.com/pileax-ai/yiitap，MIT）───
 * 精选常用集在前（保持既有 :name: 短代码兼容），全量集紧随其后；
 * keywords 取自官方英文名单词，用于搜索。 */
import emojiFullJson from "./emoji-data-full.json";

export interface EmojiEntry {
  name: string;
  emoji: string;
  keywords?: string[];
  /** 分组 slug（全量数据自带；精选集归入 common） */
  group?: string;
}

const emojiFull = emojiFullJson as EmojiEntry[];

/** 精选常用集数量（emojiLibrary 前 N 个），用于"常用"分组 */
export const COMMON_EMOJI_COUNT = emojisToName.length;

/* 箭头/符号类字符（↔ ↕ ⬅ ⌨ 等）默认是文本呈现，缺 U+FE0F 时浏览器会
 * 渲染成蓝色普通字形而非彩色 emoji；纯 BMP 字符补上变体选择符强制 emoji 呈现。 */
function normalizeGlyph(glyph: string): string {
  if (glyph.includes("\uFE0F") || glyph.includes("\u200D")) return glyph;
  const bmpOnly = [...glyph].every((ch) => (ch.codePointAt(0) ?? 0) < 0x10000);
  return bmpOnly ? glyph + "\uFE0F" : glyph;
}

export const emojiLibrary: EmojiEntry[] = [
  ...emojisToName.map((e) => ({ ...e, emoji: normalizeGlyph(e.emoji), group: "common" })),
  ...emojiFull
    .filter((e) => !emojisToName.some((c) => c.name === e.name || c.emoji === e.emoji))
    .map((e) => ({ ...e, emoji: normalizeGlyph(e.emoji) })),
];

export interface EmojiGroup {
  id: string;
  icon: string;
  labelKey: string;
}

/** 底部分类切换条（常用 + 9 大官方分组），icon 直接用 emoji 字符 */
export const EMOJI_GROUPS: EmojiGroup[] = [
  { id: "common", icon: "🕘", labelKey: "emoji.group.common" },
  { id: "smileys_emotion", icon: "😀", labelKey: "emoji.group.smileys" },
  { id: "people_body", icon: "👋", labelKey: "emoji.group.people" },
  { id: "animals_nature", icon: "🐻", labelKey: "emoji.group.animals" },
  { id: "food_drink", icon: "🍔", labelKey: "emoji.group.food" },
  { id: "travel_places", icon: "🚗", labelKey: "emoji.group.travel" },
  { id: "activities", icon: "⚽", labelKey: "emoji.group.activities" },
  { id: "objects", icon: "💡", labelKey: "emoji.group.objects" },
  { id: "symbols", icon: "🔔", labelKey: "emoji.group.symbols" },
  { id: "flags", icon: "🚩", labelKey: "emoji.group.flags" },
];

/** 根据查询字符串搜索 emoji（名字 / 英文关键词包含，下划线与空格等价） */
function matchEmoji(e: EmojiEntry, q: string) {
  const normalized = q.replace(/_/g, " ");
  if (e.name.replace(/_/g, " ").includes(normalized)) return true;
  return (e.keywords ?? []).some((k) => k.includes(normalized));
}

export function emojiSearch(query: string, limit = 12) {
  const q = query.trim().toLowerCase();
  if (!q) return emojiLibrary.slice(0, limit);
  return emojiLibrary.filter((e) => matchEmoji(e, q)).slice(0, limit);
}

/** 无截断的过滤（联想浮层用，自行控制展示条数） */
export function emojiFilter(query: string) {
  const q = query.trim().toLowerCase();
  if (!q) return emojiLibrary;
  return emojiLibrary.filter((e) => matchEmoji(e, q));
}

/** 按分组取列表（搜索时用 emojiFilter 代替） */
export function emojiByGroup(group: string) {
  return group === "common"
    ? emojiLibrary.slice(0, COMMON_EMOJI_COUNT)
    : emojiLibrary.filter((e) => e.group === group);
}
